version: "3.8"
services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    depends_on:
      - postgres
  client:
    container_name: client
    restart: always
    build: ./frontend
    depends_on:
      - backend
  nginx:
    depends_on:
      - backend
      - client
    restart: always
    build: ./nginx
    ports:
      - "80:80"
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: code_drops_crud
    expose:
      - "5432"
    ports:
      - "5432:5432"
